# configuration file for rumor-tracker

# data sources
track-twitter-queries: true
twitter-queries:
  - "covid geocode:-22.1384193,17.22279785,450mi"
track-twitter-users: false
track-youtube-channels: false
track-facebook-page: false
track-kobo-form: false
text-field-kobo-form: "test"

# data parsing
geolocate: true
geodata-locations: "nam_admbnda_adm1_nsa_ocha_20200109.geojson"
geodata-country-boundaries: "nam_admbnda_adm0_nsa_ocha_20200109.geojson"
location-input:
  - "ADM1_EN"
location-output: "ADM1_EN"
filter-by-keywords: false
translate: true            # requires Google API
analyse-sentiment: true    # requires Google API
analyse-topic: true
model-filename: "gsdmm-model-v1.pickle"
keys-to-topics-filename: "keys-to-topics-v0.2.csv"

# credentials
# all credentials are stored as secrets in Azure key vault
# the secret is a json object with some required fields; see below what is required in each case
keyvault-url: "https://global-covid-keys.vault.azure.net"
twitter-secret: "nam-rumor-tracker-twitter-secret"        # CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_SECRET
blobstorage-secret: "nam-rumor-tracker-blobstorage"       # connection_string, container
google-secret: "nam-rumor-tracker-google-service-account" # <service account json key>
kobo-secret: "kobo-secret"                                # token, asset

# data storage
"skip-datalake": false