# configuration file for rumor-tracker

# data sources
track-azure-table: false
track-twitter-queries: false
twitter-queries:
track-twitter-users: false
track-youtube-channels: false
track-facebook-page: false
track-facebook-comments: false
track-kobo-form: false
text-field-kobo-form: ""
track-telegram-groups: true

# data parsing
geolocate: false
geodata-locations: ""
geodata-country-boundaries: ""
location-input:
location-output: "ADM1_EN"
filter-by-keywords: false
translate: true
translation-model: "Google" #"HuggingFace:Helsinki-NLP/opus-mt-fr-en"
analyse-sentiment: false
sentiment-model: "Google" #"HuggingFace:finiteautomata/bertweet-base-sentiment-analysis"
analyse-topic: false
model-filename: "gsdmm-model-v1.pickle"
keys-to-topics-filename: "keys-to-topics-v0.2.csv"

# credentials
# all credentials are stored as secrets in Azure key vault
# the secret is a json object with some required fields; see below what is required in each case
keyvault-url: "https://global-covid-keys.vault.azure.net"
twitter-secret: "nam-rumor-tracker-twitter-secret" # CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_SECRET
blobstorage-secret: "nam-rumor-tracker-blobstorage" # connection_string, container
google-secret: "nam-rumor-tracker-google-service-account" # <service account json key>
kobo-secret: "kobo-secret" # token, asset
telegram-secret: "rou-telegram-secrets"
telegram-phone: "+31657019207"
telegram-channels:
  - "t.me/ukrinrom"
  - "t.me/romaniahelp2022"

# data storage
"skip-datalake": true
