# configuration file for rumor-tracker

# data sources
track-twitter-queries: false
twitter-queries: ""
track-twitter-users: false
track-youtube-channels: false
track-facebook-page: false
track-kobo-form: false
track-facebook-comments: false
text-field-kobo-form: ""
track-azure-table: true
azure-table-name: "UgandaRCCETool"
text-field-azure-table:
  - "rumors_hh"
  - "rumors_cg"

# data parsing
geolocate: false
geodata-locations: ""
geodata-country-boundaries: ""
location-input: ""
location-output: ""
filter-by-keywords: false
translate: false
translation-model: ""
analyse-sentiment: false
sentiment-model: ""
analyse-topic: true
model-directory: "UgandaRCCETool/topic_model" # relative to blob storage root directory
model-filename: "gsdmm-model-v0.pickle"
keys-to-topics-filename: "keys-to-topics-v01.csv"

# credentials
# all credentials are stored as secrets in Azure key vault
# the secret is a json object with some required fields; see below what is required in each case
keyvault-url: "https://global-covid-keys.vault.azure.net"
twitter-secret: ""
blobstorage-secret: "uga-rumor-tracker-blobstorage" # connection string and directory
table-secret: "uga-rumor-tracker-table"  # connection_string
google-secret: ""
kobo-secret: ""

# data storage
"skip-datalake": false